version: '3.8'

services:
  # --- INFRASTRUCTURE ---
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3388:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - founderlink-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - founderlink-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - founderlink-network

  # --- CORE SERVICES ---
  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    ports:
      - "8760:8760"
    networks:
      - founderlink-network

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8887:8887"
    depends_on:
      - eureka-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
    volumes:
      - ./config-repo:/app/config-repo
    networks:
      - founderlink-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8060:8060"
    depends_on:
      - eureka-service
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

  # --- BUSINESS SERVICES ---
  #  auth-service:
  #    build: ./auth-service
  #    container_name: auth-service
  #    depends_on:
  #      - mysql-db
  #      - eureka-service
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_auth_sprint?createDatabaseIfNotExist=true
  #      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
  #      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
  #      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
  #    networks:
  #      - founderlink-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8061:8061"
    depends_on:
      - mysql-db
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_auth_sprint?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mysql-db
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_user_sprint?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

  startup-service:
    build: ./startup-service
    container_name: startup-service
    depends_on:
      - mysql-db
      - rabbitmq
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_startup_sprint?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

  investment-service:
    build: ./investment-service
    container_name: investment-service
    depends_on:
      - mysql-db
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_investment_sprint?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

  team-service:
    build: ./team-service
    container_name: team-service
    depends_on:
      - mysql-db
      - eureka-service
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_team_sprint?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - mysql-db
      - rabbitmq
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_notification_sprint?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

  messaging-service:
    build: ./messaging-service
    container_name: messaging-service
    depends_on:
      - mysql-db
      - eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/founderlink_messaging_sprint?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8760/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8887
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - founderlink-network

networks:
  founderlink-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
