server.port=8061
spring.application.name=user-service

spring.datasource.url=jdbc:mysql://localhost:3306/founderlink_user_sprint?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.serviceUrl.defaultZone=http://localhost:8760/eureka/
eureka.instance.prefer-ip-address=true

springdoc.api-docs.path=/users/v3/api-docs
server.forward-headers-strategy=framework
